<?php
    $order_id = $_GET['id'];
    $order_id = str_replace("/", "", $order_id);
    $order_data = $this->getOrderData($order_id);
    //$orderId = $this->getVeratadOrderId();
    $fn = $order_data->getBillingAddress()->getFirstname();
    $ln = $order_data->getBillingAddress()->getLastname();
    $addr = $order_data->getBillingAddress()->getData("street");
    $zip = $order_data->getBillingAddress()->getData("postcode");

    $fail_title = $this->getFailTitle();
    $fail_subtitle = $this->getFailSubTitle();
    $second_attempt_success_title = $this->getSuccessTitle();
    $second_attempt_success_subtitle = $this->getSuccessSubTitle();
    $second_attempt_failure_title = $this->getSecondAttemptFailureTitle();
    $second_attempt_failure_subtitle = $this->getSecondAttemptFailureSubTitle();
    $not_eligible_title = $this->getNotEligibleTitle();
    $not_eligible_subtitle = $this->getNotEligibleSubTitle();
    $attempts_exceeded_title = $this->getAttemptsExcededTitle();
    $attempts_exceeded_subtitle = $this->getAttemptsExcededSubTitle();
?>
    <div id="text" style="display:none;">
    <h2 id="fail_title"><?php echo $fail_title; ?></h2>
    <p id="fail_subtitle"><?php echo $fail_subtitle; ?></p>

    <h2 id="success_title" style="display:none;"><?php echo $second_attempt_success_title; ?></h2>
    <p id="success_subtitle" style="display:none;"><?php echo $second_attempt_success_subtitle; ?></p>

    <h2 id="second_attempt_failure_title" style="display:none;"><?php echo $second_attempt_failure_title; ?></h2>
    <p id="second_attempt_failure_subtitle" style="display:none;"><?php echo $second_attempt_failure_subtitle; ?></p>
    </div>
    <h2 id="attempts_exceeded_title" style="display:none;"><?php echo $attempts_exceeded_title; ?></h2>
    <p id="attempts_exceeded_subtitle" style="display:none;"><?php echo $attempts_exceeded_subtitle; ?></p>

    <h2 id="not_eligible_title" style="display:none;"><?php echo $not_eligible_title; ?></h2>
    <p id="not_eligible_subtitle" style="display:none;"><?php echo $attempts_exceeded_subtitle; ?></p>

        <form name="veratad-av" method="POST" id="veratad-av" style="display:none;">
          <div style="margin-top:10px;">
            <p>Legal First Name</p>
            <input name="fn" type="text" placeholder="Legal First Name" id="fn" value ="<?php echo $fn; ?>">
          </div>
          <div style="margin-top:10px;">
            <p>Legal Last Name</p>
            <input  name="ln" type="text" placeholder="Legal Last Name" id="ln" value ="<?php echo $ln; ?>">
          </div>
          <div style="margin-top:10px;">
            <p>Street Address</p>
            <input name="addr" type="text" placeholder="Street Address" id="addr" value ="<?php echo $addr; ?>">
          </div>
          <div style="margin-top:10px;">
            <p>Zip Code</p>
            <input name="zip" type="text" placeholder="Zip Code" id="zip" value ="<?php echo $zip; ?>">
          </div>
          <div style="margin-top:10px;">
            <p>Date of Birth</p>
            <input id="dob" name="dob" placeholder="YYYYMMDD" type="text" value=""/>
          </div>
          <div style="margin-top:10px;">
            <p>Last 4 of SSN</p>
            <input name="ssn" type="text" placeholder="Last 4 SSN" id="ssn" value ="">
          </div>
          <input type="hidden" name="order_id" value="<?php echo $order_id; ?>">
          <input type="hidden" name="dcam_id" value="">
          <input type="hidden" name="shipping_diff" value="">
          <input type="hidden" name="shipping_action" value="">
          <input type="hidden" name="shipping_detail" value="">
          <input type="hidden" name="shipping_confirmation" value="">
        <div style="margin-top:10px;">
          <button type="submit" id="veratadSubmit" class="btn btn-primary btn-lg pull-right">Verify</button>
        </div>
        </form>
        <script>

        require(['jquery'],function(){
          jQuery(document).ready(function(){

                  var url = "<?php echo $block->getBaseUrl().'ageverification/attempts/checkattempts' ?>";

                  var send = jQuery("#veratad-av").serialize();

                    // send ajax
                    jQuery.ajax({
                        url: url, // url where to submit the request
                        type : "POST", // type of action POST || GET
                        dataType : 'json', // data type
                        showLoader: true,
                        data : send, // post data || get data
                        success : function(result) {
                          console.log(result);
                            var action = result.action;
                            if(action === "false"){
                              jQuery('#veratad-av').hide();
                              jQuery('#fail_title').hide();
                              jQuery('#fail_subtitle').hide();
                              jQuery('#attempts_exceeded_title').show();
                              jQuery('#attempts_exceeded_subtitle').show();
                            }else{
                              jQuery('#veratad-av').show();
                              jQuery('#text').show();
                            }
                            var eligible = result.eligible;
                            if (eligible === "false"){
                              jQuery('#veratad-av').hide();
                              jQuery('#fail_title').hide();
                              jQuery('#fail_subtitle').hide();
                              jQuery('#attempts_exceeded_title').hide();
                              jQuery('#attempts_exceeded_subtitle').hide();
                              jQuery('#not_eligible_title').show();
                              jQuery('#not_eligible_subtitle').show();
                            }
                          },
                        error: function(xhr, resp, text) {
                            console.log(xhr, resp, text);
                        }
                    })
                    return false;
            });
        });
        </script>
        <script>
        require(['jquery'],function(){
          jQuery(document).ready(function(){
                // click on button submit
                jQuery("#veratadSubmit").on('click', function(){
                  var url = "<?php echo $block->getBaseUrl().'ageverification/agematch/query' ?>";

                    // send ajax
                    jQuery.ajax({
                        url: url,
                        type : "POST",
                        dataType : 'json',
                        showLoader: true,
                        data : jQuery("#veratad-av").serialize(), // post data || get data
                        success : function(veratad) {

                            var action = veratad.action;

                            if(action === "PASS"){
                              jQuery('#veratad-av').hide();
                              jQuery('#fail_title').hide();
                              jQuery('#fail_subtitle').hide();
                              jQuery('#success_title').show();
                              jQuery('#success_subtitle').show();
                            }else{
                              jQuery('#veratad-av').hide();
                              jQuery('#fail_title').hide();
                              jQuery('#fail_subtitle').hide();
                              jQuery('#second_attempt_failure_title').show();
                              jQuery('#second_attempt_failure_subtitle').show();
                            }

                          },
                        error: function(xhr, resp, text) {
                            console.log(xhr, resp, text);
                        }
                    })
                    return false;
            });
            });
        });
        </script>
