<?php

    $order_data = $block->getOrderData();

    $dcams_id = $block->getDcamsId();

    $fn = $order_data['fn'];
    $ln = $order_data['ln'];
    $addr = $order_data['addr'];
    $state = $order_data['state'];
    $zip = $order_data['zip'];
    $order_id = $order_data['id'];
    $customer_id = $order_data['customer_id'];

    $age = $block->getAgeState($state);

    $fail_subtitle = $block->getFailSubTitle();

    $dcams_success = $block->getDcamsSuccessMessage();
    $dcams_failure = $block->getDcamsFailureMessage();

    $dcams_site = $block->getDcamsSiteName();
    $dcams_rules = $block->getDcamsRules();

    if(!empty($dcams_site)){
      $dcams_active = "true";
    }else{
      $dcams_active = "false";
    }

    if($block->getDobVisible()){
      $dob_visible = "block";
    }else{
      $dob_visible = "none";
    }

    if($block->getDobRequired()){
      $dob_required = "true";
    }else{
      $dob_required = "false";
    }

    if($block->getSsnVisible()){
      $ssn_visible = "block";
    }else{
      $ssn_visible = "none";
    }

    if($block->getSsnRequired()){
      $ssn_required = "true";
    }else{
      $ssn_required = "false";
    }

?>
<p id="fail_subtitle"><?php echo $block->escapeHtml($fail_subtitle); ?></p>

<p id="dcams_success" style="display:none;"><?php echo $block->escapeHtml($dcams_success); ?></p>
<p id="dcams_failure" style="display:none;"><?php echo $block->escapeHtml($dcams_failure); ?></p>
        <form name="veratad-av" method="POST" id="veratad-av" style="display:none;">
          <div style="margin-top:10px;">
            <p>Street Address</p>
            <input name="addr" type="text" placeholder="Street Address" id="addr" value ="<?php echo $block->escapeHtml($addr); ?>">
          </div>
          <div style="margin-top:10px;">
            <p>Zip Code</p>
            <input name="zip" type="text" placeholder="Zip Code" id="zip" value ="<?php echo $block->escapeHtml($zip); ?>">
          </div>
          <div style="margin-top:10px; display:<?php echo $block->escapeHtml($dob_visible); ?>;" >
            <p>Date of Birth</p>
            <input id="dob" name="dob" placeholder="YYYYMMDD" type="text" value=""/>
          </div>
          <div style="margin-top:10px; display:<?php echo $block->escapeHtml($ssn_visible); ?>;">
            <p>Last 4 of SSN</p>
            <input name="ssn" type="text" placeholder="Last 4 SSN" id="ssn" value ="">
          </div>
          <input type="hidden" name="fn" value="<?php echo $block->escapeHtml($fn); ?>">
          <input type="hidden" name="ln" value="<?php echo $block->escapeHtml($ln); ?>">
          <input type="hidden" name="order_id" value="<?php echo $block->escapeHtml($order_id); ?>">
          <input type="hidden" name="customer_id" value="<?php echo $block->escapeHtml($customer_id); ?>">
          <input type="hidden" name="dcam_id" value="">
          <input type="hidden" name="shipping_diff" value="">
          <input type="hidden" name="shipping_action" value="">
          <input type="hidden" name="shipping_detail" value="">
          <input type="hidden" name="shipping_confirmation" value="">
        <div style="margin-top:10px;">
          <button type="submit" id="veratadSubmit" class="btn btn-primary btn-lg pull-right">Verify</button>
        </div>
        </form>
          <button type="button" class="dcams" id="dcams_button" class="btn btn-primary btn-lg pull-right" style="display:none; margin-top:20px;">Upload Your ID</button>

        <script>
        require(['jquery'],function(){
          jQuery(document).ready(function(){
                  var url = BASE_URL + 'ageverification/attempts/checkattempts';
                  var send = jQuery("#veratad-av").serialize();
                    // send ajax
                    jQuery.ajax({
                        url: url, // url where to submit the request
                        type : "POST", // type of action POST || GET
                        dataType : 'json', // data type
                        showLoader: true,
                        data : send, // post data || get data
                        success : function(result) {
                          console.log(result);
                            var action = result.action;
                            if(action === "false"){
                              jQuery('#veratad-av').hide();
                              jQuery('#fail_subtitle').hide();
                            }else{
                              jQuery('#veratad-av').show();
                            }
                          },
                        error: function(xhr, resp, text) {
                            console.log(xhr, resp, text);
                        }
                    })
                    return false;
            });
        });
        </script>
        <script>
        require(['jquery'],function(){
          jQuery(document).ready(function(){

            function validateForm() {

              var addr = document.forms["veratad-av"]["addr"].value;
              var zip = document.forms["veratad-av"]["zip"].value;
              var dob = document.forms["veratad-av"]["dob"].value;
              var ssn = document.forms["veratad-av"]["ssn"].value;

              var ssn_required = <?php echo $block->escapeHtml($ssn_required); ?>;
              var dob_required = <?php echo $block->escapeHtml($dob_required); ?>;

              if(addr == ""){
                alert("Address is a required field.");
                return false;
              }else if(zip == ""){
                alert("Zip code is a required field.");
                return false;
              }else if(ssn == "" && ssn_required === true){
                alert("Last 4 SSN is a required field.");
                return false;
              }else if(dob == "" && dob_required === true){
                alert("Date of Birth is a required field.");
                return false;
              }
              return true;
            }


                // click on button submit
                jQuery("#veratadSubmit").on('click', function(){
                  jQuery('#fail_subtitle').hide();
                  var url = BASE_URL + 'ageverification/agematch/query';

                  valid = validateForm();

                  var dcams_active = <?php echo $block->escapeHtml($dcams_active); ?>;

                  if(valid){

                    // send ajax
                    jQuery.ajax({
                        url: url,
                        type : "POST",
                        dataType : 'json',
                        showLoader: true,
                        data : jQuery("#veratad-av").serialize(), // post data || get data
                        success : function(veratad) {
                          console.log(veratad);
                            var action = veratad.action;
                            var eligible = veratad.attempts_left;
                              if(action === "PASS"){
                                jQuery('#veratad-av').hide();
                              }else if (action === "FAIL" && eligible === true){
                                jQuery('#veratad-av').show();
                              }else{
                              jQuery('#veratad-av').hide();
                              if(dcams_active === true){
                                jQuery('.dcams').show();
                              }
                            }
                          },
                        error: function(xhr, resp, text) {
                            console.log(xhr, resp, text);
                        }
                    })
                  }else{
                    return false;
                  }
                    return false;

            });

            });
        });
        </script>
<script>
require(['jquery'],function(){
  function updateDcamsStatus(){
          var url = BASE_URL + 'ageverification/dcamsplus/update';
            // send ajax
            jQuery.ajax({
                url: url, // url where to submit the request
                type : "POST", // type of action POST || GET
                dataType : 'json', // data type
                showLoader: true,
                data : {"email": "<?php echo $block->escapeHtml($dcams_id); ?>", "order": "<?php echo $block->escapeHtml($order_id); ?>", "customer": "<?php echo $block->escapeHtml($customer_id); ?>"}, // post data || get data
                success : function(result) {
                  console.log(result);
                  },
                error: function(xhr, resp, text) {
                    console.log(xhr, resp, text);
                }
            })

  }
  jQuery(document).ready(function(){
  jQuery("#dcams_button").on('click', function(){

          var veratadModal;
          jQuery(function(){
            veratadModal = new veratad.modal({
              site: "<?php echo $block->escapeHtml($dcams_site); ?>", // veratad will provide your site name for identification.
              review: true, // set to true or false. When true it will trigger a Veratad anual review upon scan failure.
              rules: "<?php echo $block->escapeHtml($dcams_rules); ?>", //check out api.veratad.com for more rule sets
              age: "<?php echo $block->escapeHtml($age); ?>", //place the age you want to check here
              fn: "<?php echo $block->escapeHtml($fn); ?>", //customer first name
              ln: "<?php echo $block->escapeHtml($ln); ?>", //customer last name
              addr: jQuery('#addr').val(), //customer address
              zip: jQuery('#addr').val(), //customer zip code
              dob: jQuery('#dob').val(), //required - Customer Date of birth. YYYYMMDD format only.
              email: "<?php echo $block->escapeHtml($dcams_id); ?>", //required - customer email address. This is used for tracking the user.
              onOpen: function() {
                console.log('Veratad modal open');
              },
              onClose: function() {
                console.log('Veratad modal closed');
                veratadModal.close();
              },
              onSuccess: function() {
                //this is just an example. Handle the customer in your own frontend flow.
                jQuery('#dcams_success').show();
                jQuery('.dcams').hide();
                updateDcamsStatus();
                veratadModal.close();
              },
              onFailure: function() {
                //this is just an example. Handle the customer in your own frontend flow.
                jQuery('#dcams_failure').show();
                jQuery('.dcams').hide();
                updateDcamsStatus();
                veratadModal.close();
              },
            });
          veratadModal.open();
          });
        });
      });
});
    </script>
  <script src="https://verataddev.com/dcams/stable/initialize.js"></script>
