<?php

$details = $block->getVeratadDetails();
$username = $block->getCurrentUser();
$orderId = $block->veratadOrderId();
$order_action = $block->getVeratadActionOrder();

$front = $block->getDcamsFront();
$back = $block->getDcamsBack();


$status_url =  $block->escapeUrl($block->getBaseUrl().'ageverification/status/update/');

?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title">Veratad Age Verification: <?php echo $block->escapeHtml($order_action); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method">
                        <div class="admin__page-section-item-title">
                <span class="title">Verification History</span>
            </div>
            </div>
            <div class="admin__table-wrapper">
          		<table class="data-table admin__table-primary edit-order-table">
          			<thead>
          				<tr class="headings">
          					<th><span>Timestamp</span></th>
          					<th><span>Confirmation</span></th>
          					<th><span>Action</span></th>
          					<th><span>Detail</span></th>
                    <th><span>Address Type</span></th>
          					<th><span>Manual Override</span></th>
          					<th><span>User</span></th>
          				</tr>
          			</thead>
          			<tbody class="even">
                  <?php foreach ($details as $detail):
                    $timestamp = $detail['veratad_timestamp'];
                    $confirmation = $detail['veratad_confirmation'];
                    $action = $detail['veratad_action'];
                    $veratad_detail = $detail['veratad_detail'];
                    $address_type = $detail['veratad_address_type'];
                    $override = $detail['veratad_override'];
                    $override_user = $detail['veratad_override_user'];
                    ?>
          				<tr>
          					<td><?php echo  $block->escapeHtml($timestamp); ?></td>
          					<td ><?php echo $block->escapeHtml($confirmation); ?></td>
          					<td ><?php echo $block->escapeHtml($action); ?></td>
          					<td><?php echo $block->escapeHtml($veratad_detail); ?></td>
                    <td><?php echo $block->escapeHtml($address_type); ?></td>
          					<td ><?php echo $block->escapeHtml($override); ?></td>
          					<td ><?php echo $block->escapeHtml($override_user); ?></td>
          				</tr>
                  <?php endforeach; ?>
          			</tbody>
          		</table>
          	</div>




            <section class="admin__page-section order-addresses">
                <div class="admin__page-section-title">
                    <span class="title">Identity Document</span>
                </div>
                <div class="admin__page-section-content">
                    <div class="admin__page-section-item order-billing-address">
                                    <div class="admin__page-section-item-title">
                            <span class="title">Front</span>
                        </div>
                        <address class="admin__page-section-item-content">
                          <img src="https://register.veratad.com/images/ul/<?php echo $block->escapeHtml($front); ?>" height="250" width"250"></img>
            </address>
                    </div>
                                <div class="admin__page-section-item order-shipping-address">
                                            <div class="admin__page-section-item-title">
                                <span class="title">Back</span>

                            </div>
                            <address class="admin__page-section-item-content">
                              <img src="https://register.veratad.com/images/ul/<?php echo $block->escapeHtml($back); ?>" height="250" width"250"></img>

            </address>
                        </div>
                        </div>
            </section>
            <div class="admin__field">
              <form id="veratad">
              <input type="hidden" name="order_id" value="<?php echo $block->escapeHtml($orderId); ?>">
              <input type="hidden" name="username" value="<?php echo $block->escapeHtml($username); ?>">
              <input type="hidden" name="front_id" value="<?php echo $block->escapeHtml($front); ?>">
              <input type="hidden" name="back_id" value="<?php echo $block->escapeHtml($back); ?>">
                <label for="status" class="admin__field-label">Change Verification Status</label>
                <div class="admin__field-control" style="margin-top:10px;">
                    <select name="status" id="veratad_status" class="admin__control-select">
                    <option>Select an action</option>
                    <option value="PASS">PASS</option>
                    <option value="FAIL">FAIL</option>
                    </select>
                    <button id="changeStatus" style="margin-left:10px;">Update</button>
                </div>
            </div>
          </form>

        </div>
  </section>

  <script>

  require(['jquery'],function(){
    jQuery(document).ready(function(){
          // click on button submit
          jQuery("#changeStatus").on('click', function(){
            var url = "<?php echo $status_url; ?>";
            var send = jQuery("#veratad").serialize();
            console.log(send);
              // send ajax
              jQuery.ajax({
                  url: url, // url where to submit the request
                  type : "POST", // type of action POST || GET
                  dataType : 'json', // data type
                  showLoader: true,
                  data : send, // post data || get data
                  success : function() {
                      location.reload();
                    },
                  error: function(xhr, resp, text) {
                      console.log(xhr, resp, text);
                  }
              })
              return false;
      });
      });
  });
  </script>
