<?php

        $helper = $this->helper('Veratad\AgeVerification\Helper\Data');
        $customer = $helper->getVeratadAccountAction();
        $action = $customer[0]['veratad_action'];

        $details = $helper->getVeratadAccountHistoryHelper();
        $username = $helper->getCurrentUserVeratad();

        $customerid = $helper->getVeratadCustomerId();

?>
<div class="admin__page-section-title">
    <span class="title">Age Verification: <?php echo $action; ?></span>
</div>
<div class="admin__page-section-content">
    <div class="admin__page-section-item order-payment-method">
                    <div class="admin__page-section-item-title">
            <span class="title">Verification History</span>
        </div>
        </div>
<div class="admin__table-wrapper">
  <table class="data-table admin__table-primary edit-order-table">
    <thead>
      <tr class="headings">
        <th><span>Timestamp</span></th>
        <th><span>Confirmation</span></th>
        <th><span>Action</span></th>
        <th><span>Detail</span></th>
        <th><span>Address Type</span></th>
        <th><span>Manual Override</span></th>
        <th><span>User</span></th>
      </tr>
    </thead>
    <tbody class="even">
      <?php foreach ($details as $detail): ?>
      <tr>
        <td><?php echo $detail['veratad_timestamp'] ?></td>
        <td ><?php echo $detail['veratad_confirmation'] ?></td>
        <td ><?php echo $detail['veratad_action'] ?></td>
        <td><?php echo $detail['veratad_detail'] ?></td>
        <td><?php echo $detail['veratad_address_type'] ?></td>
        <td ><?php echo $detail['veratad_override'] ?></td>
        <td ><?php echo $detail['veratad_override_user'] ?></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
<div class="admin__field">
  <form id="veratad">
  <input type="hidden" name="username" value="<?php echo $username ?>">
  <input type="hidden" name="id" value="<?php echo $customerid ?>">
    <label for="status" class="admin__field-label">Change Verification Status</label>
    <div class="admin__field-control" style="margin-top:10px;">
        <select name="status" id="veratad_status" class="admin__control-select">
        <option>Select an action</option>
        <option value="PASS">PASS</option>
        <option value="FAIL">FAIL</option>
        </select>
        <button id="changeStatus" style="margin-left:10px;">Update</button>
    </div>
</div>
</form>

</div>


<script>

require(['jquery'],function(){
  jQuery(document).ready(function(){
        // click on button submit
        jQuery("#changeStatus").on('click', function(){
          var url = "<?php echo $block->getBaseUrl().'ageverification/customer/update/' ?>";
          console.log(url);
          var send = jQuery("#veratad").serialize();
          console.log(send);
            // send ajax
            jQuery.ajax({
                url: url, // url where to submit the request
                type : "POST", // type of action POST || GET
                dataType : 'json', // data type
                showLoader: true,
                data : send, // post data || get data
                success : function() {
                    location.reload();
                  },
                error: function(xhr, resp, text) {
                    console.log(xhr, resp, text);
                }
            })
            return false;
    });
    });
});
</script>
